int intSize();
int doubleSize();
int pointerSize();
int changeValue();
int withinSameBlock(int *, int *);
int withinArray(int *, int, int *);
void swapInts(int *, int *);
int stringLength(char *);
void stringAppend(char *, char *);
int endianExperiment(int*);
void selectionSort(int *, int);
